name: SERVER CI

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'server/**'

  workflow_dispatch:

env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mindmap?schema=public
  APP_PORT: 3000


jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Generate Prisma Client
        run: cd server && npx prisma generate
      - name: Install dependencies
        run: cd server && npm ci
      - name: Run tests
        run: cd server && npm run test
      - name: Build
        run: cd server && npm run build --if-present